spring:
  application:
    name: proxy-service

server:
  port: 8081
  servlet:
    context-path: /

zuul:
  routes:
    api:
      path: /**
      url: http://localhost:8080/
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      api:
        - limit: 5
          refresh-interval: 10
          type:
            - url
        - limit: 5
          refresh-interval: 10
          type:
            - origin
        - limit: 10
          refresh-interval: 10
          type:
            - origin
            - url


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
