spring:
  application:
    name: proxy-service

server:
  port: 8080
  servlet:
    context-path: /

zuul:
  routes:
    api:
      path: /**
      url: http://localhost:8083/
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      api:
        - limit: 15
          refresh-interval: 2
          type:
            - url
        #- limit: 5
        #  refresh-interval: 10
        #  type:
        #    - origin
        #- limit: 10
        #  refresh-interval: 10
        #  type:
        #    - origin
        #    - url

control-service:
  ribbon:
    eureka:
      enabled: true
    listOfServers: http://localhost:8081

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
